package io.carpe.hyperscan.wrapper.flags;

/**
 * Flags influencing the matching behaviour of the scanner for a particular HyperscanExpression
 */
public enum ChimeraExpressionFlag implements HyperscanBitFlag {

    /**
     * Matching will be performed case-insensitively.
     */
    CASELESS(1),

    /**
     * Matching a . will not exclude newlines.
     */
    DOTALL(2),


    /**
     * ^ and $ anchors match any newlines in data.
     */
    MULTILINE(4),

    /**
     * Only one match will be generated by the expression per stream.
     */
    SINGLEMATCH(8),

    /**
     * Treat this pattern as a sequence of UTF-8 characters.
     */
    UTF8(32),

    /**
     * Use Unicode properties for character classes.
     */
    UCP(64),

    /**
     * Extract match text for match object.
     */
    EXTRACT_MATCHED();

    private final Integer bits;

    ChimeraExpressionFlag(int bitPosition) {
        this.bits = bitPosition;
    }

    ChimeraExpressionFlag() {
        this.bits = null;
    }


    /**
     * Get the significant bits for the flag
     *
     * @return int containing the significant bit for the flag
     */
    public Integer getBits() {
        return bits;
    }
}
